import type { LeadInboxRecord } from "../../../types";

export const generateLeadInbox = (): LeadInboxRecord[] => [
  {
    assigned_sales_id: 0,
    captured_at: "2026-09-28T04:00:00.000Z",
    city: "اهواز",
    contact_email: null,
    contact_name: "واحد تدارکات",
    contact_phone: "06100000000",
    created_at: "2026-09-28T04:00:00.000Z",
    deadline: "2026-10-05",
    description: "استعلام تأمین پنل و اینورتر خورشیدی",
    estimated_amount: 4_500_000_000,
    estimated_currency: "IRR",
    id: 1,
    organization_name: "سازمان نمونه خوزستان",
    priority: "high",
    province: "خوزستان",
    raw_payload: { fixture: true, source: "tender-radar-demo" },
    source: "tender_radar",
    source_record_id: "SETAD-DEMO-0001",
    source_url: "https://example.test/tender/SETAD-DEMO-0001",
    status: "qualified",
    title: "تأمین تجهیزات نیروگاه خورشیدی",
    updated_at: "2026-09-28T04:00:00.000Z",
  },
  {
    assigned_sales_id: null,
    captured_at: "2026-09-28T03:00:00.000Z",
    city: "تهران",
    contact_email: null,
    contact_name: null,
    contact_phone: "09120000000",
    created_at: "2026-09-28T03:00:00.000Z",
    deadline: null,
    description: "درخواست موجودی باتری لیتیومی",
    estimated_amount: null,
    estimated_currency: null,
    id: 2,
    organization_name: null,
    priority: "normal",
    province: "تهران",
    raw_payload: { fixture: true, source: "bale-market-demo" },
    source: "bale_market",
    source_record_id: "BALE-DEMO-0001",
    source_url: null,
    status: "reviewing",
    title: "خرید باتری لیتیومی ۱۶ کیلووات‌ساعت",
    updated_at: "2026-09-28T03:00:00.000Z",
  },
];
