--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

-- Inbound leads remain quarantined from core CRM records. Integrations write
-- here through server-side credentials; authenticated staff may triage only
-- the normalized fields exposed by the product.
create table public.lead_inbox (
    id bigint generated by default as identity primary key,
    source text not null,
    source_record_id text not null,
    source_url text,
    title text not null,
    organization_name text,
    contact_name text,
    contact_phone text,
    contact_email extensions.citext,
    province text,
    city text,
    description text,
    estimated_amount bigint,
    estimated_currency text,
    deadline date,
    status text not null default 'new',
    priority text not null default 'normal',
    raw_payload jsonb not null default '{}'::jsonb,
    captured_at timestamp with time zone not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    assigned_sales_id bigint,
    constraint lead_inbox_source_check check (
        source in ('tender_radar', 'bale_market', 'website', 'manual', 'import')
    ),
    constraint lead_inbox_source_record_id_check check (length(btrim(source_record_id)) > 0),
    constraint lead_inbox_title_check check (length(btrim(title)) > 0),
    constraint lead_inbox_source_url_check check (
        source_url is null or source_url ~ '^https?://'
    ),
    constraint lead_inbox_status_check check (
        status in ('new', 'reviewing', 'qualified', 'rejected', 'converted')
    ),
    constraint lead_inbox_priority_check check (
        priority in ('low', 'normal', 'high', 'urgent')
    ),
    constraint lead_inbox_raw_payload_check check (jsonb_typeof(raw_payload) = 'object'),
    constraint lead_inbox_estimate_check check (
        (estimated_amount is null and estimated_currency is null)
        or
        (estimated_amount >= 0 and estimated_currency ~ '^[A-Z]{3}$')
    ),
    constraint lead_inbox_source_record_key unique (source, source_record_id)
);

-- A conversion is immutable provenance linking one raw lead to the explicitly
-- created core records. One lead and one deal can appear only once.
create table public.lead_conversions (
    id bigint generated by default as identity primary key,
    lead_id bigint not null unique,
    company_id bigint not null,
    contact_id bigint,
    deal_id bigint not null unique,
    converted_by_sales_id bigint not null,
    converted_at timestamp with time zone not null default now()
);

-- Tender records are created only after explicit review/import from Lead Inbox.
-- SETAD identifiers, aggregator identity, publication dates and deadlines remain
-- separate so a copied or inferred value cannot silently become official truth.
create table public.tender_opportunities (
    id bigint generated by default as identity primary key,
    lead_id bigint not null unique,
    source text not null,
    aggregator_record_id text,
    opportunity_type text not null,
    official_need_no text,
    official_tender_no text,
    title text not null,
    description text,
    organizer text,
    province text,
    city text,
    publish_date date,
    document_deadline date,
    submission_deadline date,
    official_source_url text,
    aggregator_source_url text,
    domain text not null,
    trade text,
    category text,
    verification_status text not null default 'pending_setad_verification',
    radar_score smallint,
    radar_grade text,
    fallback_fingerprint text not null,
    assigned_sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint tender_opportunities_source_check check (
        source in ('tender_radar', 'setad', 'manual')
    ),
    constraint tender_opportunities_type_check check (
        opportunity_type in ('inquiry', 'tender')
    ),
    constraint tender_opportunities_official_identifier_check check (
        (opportunity_type = 'inquiry' and official_tender_no is null)
        or
        (opportunity_type = 'tender' and official_need_no is null)
    ),
    constraint tender_opportunities_need_no_check check (
        official_need_no is null or length(btrim(official_need_no)) > 0
    ),
    constraint tender_opportunities_tender_no_check check (
        official_tender_no is null or length(btrim(official_tender_no)) > 0
    ),
    constraint tender_opportunities_aggregator_id_check check (
        aggregator_record_id is null or length(btrim(aggregator_record_id)) > 0
    ),
    constraint tender_opportunities_domain_check check (
        domain in ('renewable_energy', 'security_systems')
    ),
    constraint tender_opportunities_verification_check check (
        verification_status in (
            'setad_verified',
            'pending_setad_verification',
            'data_conflict'
        )
    ),
    constraint tender_opportunities_radar_pair_check check (
        (radar_score is null and radar_grade is null)
        or
        (radar_score between 0 and 100 and radar_grade in ('A', 'B', 'C'))
    ),
    constraint tender_opportunities_official_url_check check (
        official_source_url is null or official_source_url ~ '^https://(eproc|etend)\.setadiran\.ir/'
    ),
    constraint tender_opportunities_aggregator_url_check check (
        aggregator_source_url is null or aggregator_source_url ~ '^https?://'
    ),
    constraint tender_opportunities_fingerprint_check check (
        length(btrim(fallback_fingerprint)) > 0
    )
);

create table public.tender_pipeline_entries (
    id bigint generated by default as identity primary key,
    opportunity_id bigint not null unique,
    stage text not null default 'documents',
    documents_status text not null default 'not_started',
    technical_review_status text not null default 'not_started',
    pricing_status text not null default 'not_started',
    participation_decision text not null default 'undecided',
    result_status text not null default 'pending',
    assigned_sales_id bigint,
    notes text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint tender_pipeline_stage_check check (
        stage in ('documents', 'technical_review', 'pricing', 'participation_decision', 'result')
    ),
    constraint tender_pipeline_documents_status_check check (
        documents_status in ('not_started', 'requested', 'received', 'complete')
    ),
    constraint tender_pipeline_technical_status_check check (
        technical_review_status in ('not_started', 'in_review', 'approved', 'rejected')
    ),
    constraint tender_pipeline_pricing_status_check check (
        pricing_status in ('not_started', 'in_progress', 'approved')
    ),
    constraint tender_pipeline_decision_check check (
        participation_decision in ('undecided', 'bid', 'no_bid')
    ),
    constraint tender_pipeline_result_check check (
        result_status in ('pending', 'won', 'lost', 'cancelled')
    )
);

create table public.tender_saved_searches (
    id bigint generated by default as identity primary key,
    name text not null,
    domain text not null,
    opportunity_type text,
    provinces text[] not null default '{}',
    cities text[] not null default '{}',
    keywords text[] not null default '{}',
    trade text,
    category text,
    organizer text,
    publish_from date,
    publish_to date,
    deadline_from date,
    deadline_to date,
    statuses text[] not null default '{}',
    active boolean not null default true,
    owner_sales_id bigint not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint tender_saved_searches_name_check check (length(btrim(name)) > 0),
    constraint tender_saved_searches_domain_check check (
        domain in ('renewable_energy', 'security_systems')
    ),
    constraint tender_saved_searches_type_check check (
        opportunity_type is null or opportunity_type in ('inquiry', 'tender')
    ),
    constraint tender_saved_searches_publish_range_check check (
        publish_to is null or publish_from is null or publish_to >= publish_from
    ),
    constraint tender_saved_searches_deadline_range_check check (
        deadline_to is null or deadline_from is null or deadline_to >= deadline_from
    )
);

-- Append-only observations transcribed by an authorized user from an official
-- SETAD browser session. Keeping these rows separate preserves both the Radar
-- assertion and the official observation when they conflict.
create table public.tender_setad_verifications (
    id bigint generated by default as identity primary key,
    opportunity_id bigint not null,
    opportunity_type text not null,
    official_need_no text,
    official_tender_no text,
    title text not null,
    description text,
    organizer text,
    province text,
    city text,
    publish_date date,
    document_deadline date,
    submission_deadline date,
    official_source_url text not null,
    verification_status text not null,
    checked_by_sales_id bigint not null,
    checked_at timestamp with time zone not null default now(),
    constraint tender_setad_verifications_type_check check (
        opportunity_type in ('inquiry', 'tender')
    ),
    constraint tender_setad_verifications_identifier_check check (
        (opportunity_type = 'inquiry'
            and official_need_no is not null
            and official_tender_no is null)
        or
        (opportunity_type = 'tender'
            and official_tender_no is not null
            and official_need_no is null)
    ),
    constraint tender_setad_verifications_title_check check (
        length(btrim(title)) > 0
    ),
    constraint tender_setad_verifications_status_check check (
        verification_status in ('setad_verified', 'data_conflict')
    ),
    constraint tender_setad_verifications_url_check check (
        (opportunity_type = 'inquiry'
            and official_source_url = 'https://eproc.setadiran.ir/eproc/entry.do')
        or
        (opportunity_type = 'tender'
            and official_source_url = 'https://etend.setadiran.ir/etend/index.action')
    )
);

-- Audit events are append-only and deliberately exclude credentials, cookies,
-- OTP values, CAPTCHA material and raw provider payloads.
create table public.tender_audit_log (
    id bigint generated by default as identity primary key,
    opportunity_id bigint,
    event_type text not null,
    actor_sales_id bigint not null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamp with time zone not null default now(),
    constraint tender_audit_log_event_check check (length(btrim(event_type)) > 0),
    constraint tender_audit_log_metadata_check check (jsonb_typeof(metadata) = 'object'),
    constraint tender_audit_log_sensitive_keys_check check (
        not (
            metadata ? 'password'
            or metadata ? 'credential'
            or metadata ? 'cookie'
            or metadata ? 'captcha'
            or metadata ? 'otp'
            or metadata ? 'token'
            or metadata ? 'raw_payload'
        )
    )
);

-- Delivery projects are created from won deals. deal_id is unique to preserve
-- provenance and prevent the same commercial value from becoming two projects.
create table public.projects (
    id bigint generated by default as identity primary key,
    name text not null,
    code text not null unique,
    deal_id bigint not null unique,
    company_id bigint not null,
    status text not null default 'planned',
    contract_amount bigint not null,
    currency text not null,
    start_date date,
    target_end_date date,
    completed_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    sales_id bigint,
    constraint projects_status_check check (
        status in ('planned', 'active', 'on_hold', 'completed', 'cancelled')
    ),
    constraint projects_contract_amount_check check (contract_amount >= 0),
    constraint projects_currency_check check (currency ~ '^[A-Z]{3}$'),
    constraint projects_id_currency_key unique (id, currency),
    constraint projects_date_order_check check (
        target_end_date is null or start_date is null or target_end_date >= start_date
    )
);

-- Planned and actual values live on the same line. Reports aggregate them in
-- separate columns and use greatest(planned, actual) for forecast, never their sum.
create table public.project_cost_items (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    category text not null,
    description text not null,
    planned_amount bigint not null default 0,
    actual_amount bigint not null default 0,
    currency text not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    sales_id bigint,
    constraint project_cost_items_category_check check (
        category in ('equipment', 'labor', 'subcontract', 'transport', 'permit', 'other')
    ),
    constraint project_cost_items_planned_amount_check check (planned_amount >= 0),
    constraint project_cost_items_actual_amount_check check (actual_amount >= 0),
    constraint project_cost_items_currency_check check (currency ~ '^[A-Z]{3}$'),
    constraint project_cost_items_identity_key unique (id, project_id, currency)
);

-- Procurement commitments are operational obligations. They are deliberately
-- separate from actual costs and future payment/transaction ledgers.
create table public.procurement_commitments (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    project_cost_item_id bigint not null,
    supplier_company_id bigint,
    reference text not null unique,
    status text not null default 'draft',
    amount bigint not null,
    currency text not null,
    expected_on date,
    received_on date,
    notes text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    sales_id bigint,
    constraint procurement_commitments_status_check check (
        status in ('draft', 'approved', 'ordered', 'received', 'cancelled')
    ),
    constraint procurement_commitments_amount_check check (amount >= 0),
    constraint procurement_commitments_currency_check check (currency ~ '^[A-Z]{3}$'),
    constraint procurement_commitments_identity_key unique (id, project_id, currency),
    constraint procurement_commitments_received_date_check check (
        status <> 'received' or received_on is not null
    )
);

-- Receivables and payables are separate obligation ledgers. Settlement is
-- derived from linked transactions rather than copied into mutable totals.
create table public.financial_receivables (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    company_id bigint not null,
    reference text not null unique,
    amount bigint not null,
    currency text not null,
    issued_on date not null,
    due_on date not null,
    cancelled_at timestamp with time zone,
    notes text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    sales_id bigint,
    constraint financial_receivables_amount_check check (amount > 0),
    constraint financial_receivables_currency_check check (currency ~ '^[A-Z]{3}$'),
    constraint financial_receivables_date_order_check check (due_on >= issued_on),
    constraint financial_receivables_identity_key unique (id, currency)
);

create table public.financial_payables (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    procurement_commitment_id bigint,
    company_id bigint not null,
    reference text not null unique,
    amount bigint not null,
    currency text not null,
    issued_on date not null,
    due_on date not null,
    cancelled_at timestamp with time zone,
    notes text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    sales_id bigint,
    constraint financial_payables_amount_check check (amount > 0),
    constraint financial_payables_currency_check check (currency ~ '^[A-Z]{3}$'),
    constraint financial_payables_date_order_check check (due_on >= issued_on),
    constraint financial_payables_identity_key unique (id, currency)
);

-- Transactions record cash movement and settle exactly one source ledger.
-- Procurement commitments and project contract snapshots never post here directly.
create table public.financial_transactions (
    id bigint generated by default as identity primary key,
    receivable_id bigint,
    payable_id bigint,
    reference text not null unique,
    direction text not null,
    amount bigint not null,
    currency text not null,
    occurred_at timestamp with time zone not null,
    method text not null,
    notes text,
    created_at timestamp with time zone not null default now(),
    sales_id bigint,
    constraint financial_transactions_direction_check check (
        direction in ('inflow', 'outflow')
    ),
    constraint financial_transactions_method_check check (
        method in ('bank', 'cash', 'card', 'cheque', 'other')
    ),
    constraint financial_transactions_amount_check check (amount > 0),
    constraint financial_transactions_currency_check check (currency ~ '^[A-Z]{3}$'),
    constraint financial_transactions_source_direction_check check (
        (receivable_id is not null and payable_id is null and direction = 'inflow')
        or
        (receivable_id is null and payable_id is not null and direction = 'outflow')
    )
);

-- Inventory is quantity-only. Procurement status, finance ledgers and project
-- costs never post stock automatically; every change is an explicit movement.
create table public.inventory_locations (
    id bigint generated by default as identity primary key,
    code text not null unique,
    name text not null,
    active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table public.inventory_items (
    id bigint generated by default as identity primary key,
    sku text not null unique,
    name text not null,
    unit text not null,
    reorder_level numeric(18, 3) not null default 0,
    active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint inventory_items_unit_check check (
        unit in ('piece', 'meter', 'kilogram', 'liter', 'set', 'other')
    ),
    constraint inventory_items_reorder_level_check check (reorder_level >= 0)
);

create table public.inventory_movements (
    id bigint generated by default as identity primary key,
    item_id bigint not null,
    location_id bigint not null,
    procurement_commitment_id bigint,
    project_id bigint,
    reference text not null unique,
    type text not null,
    quantity numeric(18, 3) not null,
    occurred_at timestamp with time zone not null,
    notes text,
    created_at timestamp with time zone not null default now(),
    sales_id bigint,
    constraint inventory_movements_type_check check (
        type in ('receipt', 'issue', 'adjustment_in', 'adjustment_out')
    ),
    constraint inventory_movements_quantity_check check (quantity > 0),
    constraint inventory_movements_source_check check (
        not (procurement_commitment_id is not null and project_id is not null)
        and (procurement_commitment_id is null or type = 'receipt')
        and (project_id is null or type = 'issue')
    )
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    phone text,
    administrator boolean not null,
    role text not null default 'sales',
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false,
    secondary_emails jsonb not null default '[]'::jsonb,
    constraint sales_secondary_emails_is_array check (jsonb_typeof(secondary_emails) = 'array'),
    constraint sales_phone_e164_check check (phone is null or phone ~ '^\+[1-9][0-9]{7,14}$'),
    constraint sales_role_check check (role in ('admin', 'manager', 'sales', 'project', 'finance', 'inventory', 'viewer')),
    constraint sales_admin_role_consistent check (administrator = (role = 'admin'))
);

create unique index uq__sales__user_id on public.sales using btree (user_id);
create unique index uq__sales__phone on public.sales using btree (phone) where phone is not null;

create table public.daily_work_reports (
    id bigint generated by default as identity primary key,
    sales_id bigint not null,
    work_date date not null default current_date,
    achievements text not null,
    blockers text not null default '',
    next_steps text not null default '',
    minutes_worked integer not null default 0,
    created_at timestamp with time zone not null default now(),
    constraint daily_work_reports_achievements_check check (length(btrim(achievements)) > 0),
    constraint daily_work_reports_minutes_check check (minutes_worked between 0 and 1440),
    constraint daily_work_reports_sales_date_key unique (sales_id, work_date)
);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.lead_inbox
    add constraint lead_inbox_assigned_sales_id_fkey foreign key (assigned_sales_id) references public.sales(id) on update cascade on delete set null;

alter table public.lead_conversions
    add constraint lead_conversions_lead_id_fkey foreign key (lead_id) references public.lead_inbox(id) on update cascade on delete restrict;

alter table public.tender_opportunities
    add constraint tender_opportunities_lead_id_fkey foreign key (lead_id) references public.lead_inbox(id) on update cascade on delete restrict;

alter table public.tender_opportunities
    add constraint tender_opportunities_sales_id_fkey foreign key (assigned_sales_id) references public.sales(id);

alter table public.tender_pipeline_entries
    add constraint tender_pipeline_entries_opportunity_id_fkey foreign key (opportunity_id) references public.tender_opportunities(id) on update cascade on delete restrict;

alter table public.tender_pipeline_entries
    add constraint tender_pipeline_entries_sales_id_fkey foreign key (assigned_sales_id) references public.sales(id);

alter table public.tender_saved_searches
    add constraint tender_saved_searches_owner_fkey foreign key (owner_sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.tender_setad_verifications
    add constraint tender_setad_verifications_opportunity_id_fkey foreign key (opportunity_id) references public.tender_opportunities(id) on update cascade on delete restrict;

alter table public.tender_setad_verifications
    add constraint tender_setad_verifications_checked_by_fkey foreign key (checked_by_sales_id) references public.sales(id);

alter table public.tender_audit_log
    add constraint tender_audit_log_opportunity_id_fkey foreign key (opportunity_id) references public.tender_opportunities(id) on update cascade on delete restrict;

alter table public.tender_audit_log
    add constraint tender_audit_log_actor_fkey foreign key (actor_sales_id) references public.sales(id);

alter table public.lead_conversions
    add constraint lead_conversions_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete restrict;

alter table public.lead_conversions
    add constraint lead_conversions_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete restrict;

alter table public.lead_conversions
    add constraint lead_conversions_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete restrict;

alter table public.lead_conversions
    add constraint lead_conversions_sales_id_fkey foreign key (converted_by_sales_id) references public.sales(id) on update cascade on delete restrict;

alter table public.projects
    add constraint projects_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete restrict;

alter table public.projects
    add constraint projects_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete restrict;

alter table public.projects
    add constraint projects_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.project_cost_items
    add constraint project_cost_items_project_currency_fkey foreign key (project_id, currency) references public.projects(id, currency) on update cascade on delete cascade;

alter table public.project_cost_items
    add constraint project_cost_items_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.procurement_commitments
    add constraint procurement_commitments_cost_item_fkey foreign key (project_cost_item_id, project_id, currency) references public.project_cost_items(id, project_id, currency) on update cascade on delete restrict;

alter table public.procurement_commitments
    add constraint procurement_commitments_supplier_company_id_fkey foreign key (supplier_company_id) references public.companies(id) on update cascade on delete restrict;

alter table public.procurement_commitments
    add constraint procurement_commitments_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.financial_receivables
    add constraint financial_receivables_project_currency_fkey foreign key (project_id, currency) references public.projects(id, currency) on update cascade on delete restrict;

alter table public.financial_receivables
    add constraint financial_receivables_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete restrict;

alter table public.financial_receivables
    add constraint financial_receivables_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.financial_payables
    add constraint financial_payables_project_currency_fkey foreign key (project_id, currency) references public.projects(id, currency) on update cascade on delete restrict;

alter table public.financial_payables
    add constraint financial_payables_procurement_fkey foreign key (procurement_commitment_id, project_id, currency) references public.procurement_commitments(id, project_id, currency) on update cascade on delete restrict;

alter table public.financial_payables
    add constraint financial_payables_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete restrict;

alter table public.financial_payables
    add constraint financial_payables_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.financial_transactions
    add constraint financial_transactions_receivable_currency_fkey foreign key (receivable_id, currency) references public.financial_receivables(id, currency) on update cascade on delete restrict;

alter table public.financial_transactions
    add constraint financial_transactions_payable_currency_fkey foreign key (payable_id, currency) references public.financial_payables(id, currency) on update cascade on delete restrict;

alter table public.financial_transactions
    add constraint financial_transactions_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.inventory_movements
    add constraint inventory_movements_item_id_fkey foreign key (item_id) references public.inventory_items(id) on update cascade on delete restrict;

alter table public.inventory_movements
    add constraint inventory_movements_location_id_fkey foreign key (location_id) references public.inventory_locations(id) on update cascade on delete restrict;

alter table public.inventory_movements
    add constraint inventory_movements_procurement_id_fkey foreign key (procurement_commitment_id) references public.procurement_commitments(id) on update cascade on delete restrict;

alter table public.inventory_movements
    add constraint inventory_movements_project_id_fkey foreign key (project_id) references public.projects(id) on update cascade on delete restrict;

alter table public.inventory_movements
    add constraint inventory_movements_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.daily_work_reports
    add constraint daily_work_reports_sales_id_fkey foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);
create index lead_inbox_status_captured_at_idx on public.lead_inbox using btree (status, captured_at desc);
create index lead_inbox_assigned_sales_id_idx on public.lead_inbox using btree (assigned_sales_id);
create index lead_inbox_source_idx on public.lead_inbox using btree (source);
create index lead_conversions_company_id_idx on public.lead_conversions using btree (company_id);
create index lead_conversions_contact_id_idx on public.lead_conversions using btree (contact_id);
create index lead_conversions_sales_id_idx on public.lead_conversions using btree (converted_by_sales_id);
create unique index tender_opportunities_source_record_key on public.tender_opportunities using btree (source, aggregator_record_id) where aggregator_record_id is not null;
create unique index tender_opportunities_need_no_key on public.tender_opportunities using btree (official_need_no) where official_need_no is not null;
create unique index tender_opportunities_tender_no_key on public.tender_opportunities using btree (official_tender_no) where official_tender_no is not null;
create unique index tender_opportunities_fallback_fingerprint_key on public.tender_opportunities using btree (fallback_fingerprint) where official_need_no is null and official_tender_no is null and aggregator_record_id is null;
create index tender_opportunities_assignment_idx on public.tender_opportunities using btree (assigned_sales_id, verification_status);
create index tender_pipeline_entries_assignment_idx on public.tender_pipeline_entries using btree (assigned_sales_id, stage);
create index tender_saved_searches_owner_idx on public.tender_saved_searches using btree (owner_sales_id, active);
create unique index tender_saved_searches_owner_name_key on public.tender_saved_searches using btree (owner_sales_id, lower(btrim(name)));
create index tender_setad_verifications_opportunity_idx on public.tender_setad_verifications using btree (opportunity_id, checked_at desc);
create unique index tender_setad_verifications_need_no_key on public.tender_setad_verifications using btree (official_need_no) where verification_status = 'setad_verified' and official_need_no is not null;
create unique index tender_setad_verifications_tender_no_key on public.tender_setad_verifications using btree (official_tender_no) where verification_status = 'setad_verified' and official_tender_no is not null;
create index tender_audit_log_opportunity_idx on public.tender_audit_log using btree (opportunity_id, created_at desc);
create index projects_company_id_idx on public.projects using btree (company_id);
create index projects_sales_id_idx on public.projects using btree (sales_id);
create index daily_work_reports_work_date_idx on public.daily_work_reports using btree (work_date desc);
create index project_cost_items_project_id_idx on public.project_cost_items using btree (project_id);
create index project_cost_items_sales_id_idx on public.project_cost_items using btree (sales_id);
create index procurement_commitments_project_id_idx on public.procurement_commitments using btree (project_id);
create index procurement_commitments_cost_item_id_idx on public.procurement_commitments using btree (project_cost_item_id);
create index procurement_commitments_supplier_company_id_idx on public.procurement_commitments using btree (supplier_company_id);
create index procurement_commitments_sales_id_idx on public.procurement_commitments using btree (sales_id);
create index financial_receivables_project_id_idx on public.financial_receivables using btree (project_id);
create index financial_receivables_company_id_idx on public.financial_receivables using btree (company_id);
create index financial_receivables_sales_id_idx on public.financial_receivables using btree (sales_id);
create index financial_payables_project_id_idx on public.financial_payables using btree (project_id);
create index financial_payables_procurement_id_idx on public.financial_payables using btree (procurement_commitment_id);
create index financial_payables_company_id_idx on public.financial_payables using btree (company_id);
create index financial_payables_sales_id_idx on public.financial_payables using btree (sales_id);
create index financial_transactions_receivable_id_idx on public.financial_transactions using btree (receivable_id);
create index financial_transactions_payable_id_idx on public.financial_transactions using btree (payable_id);
create index financial_transactions_sales_id_idx on public.financial_transactions using btree (sales_id);
create index inventory_movements_item_id_idx on public.inventory_movements using btree (item_id);
create index inventory_movements_location_id_idx on public.inventory_movements using btree (location_id);
create index inventory_movements_procurement_id_idx on public.inventory_movements using btree (procurement_commitment_id);
create index inventory_movements_project_id_idx on public.inventory_movements using btree (project_id);
create index inventory_movements_sales_id_idx on public.inventory_movements using btree (sales_id);
